apiVersion: v1
data:
  credentials: VzJGa2JXbHVhWE4wY21GMGIzSmRDbUYzYzE5aFkyTmxjM05mYTJWNVgybGtQVUZMU1VGWk5VaExNak16UzBJM04xRklTRFl5Q21GM2MxOXpaV055WlhSZllXTmpaWE56WDJ0bGVUMVlOV1ZyU0RnellqSnpZbXh4U0dGRFIwTm1jMkYxWVVsMFlVTnBjM05sY1VsWVNWVkpNMVJoQ2c9PQ==
kind: Secret
metadata:
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:credentials: {}
      f:type: {}
    manager: kubectl
    operation: Update
    time: 2021-10-31T20:10:09Z
  name: aws-secret
  namespace: default
type: Opaque
