version: "3"
services:
  reverseproxy:
      image: udagram-reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed
  backend-user:
    image: udagram-api-user
    environment:
      UDC_POSTGRES_USERNAME: $UDC_POSTGRES_USERNAME
      UDC_POSTGRES_PASSWORD: $UDC_POSTGRES_PASSWORD
      UDC_POSTGRES_DB: $UDC_POSTGRES_DB
      UDC_POSTGRES_HOST: $UDC_POSTGRES_HOST
      UDC_AWS_REGION: $UDC_AWS_REGION
      UDC_AWS_PROFILE: $UDC_AWS_PROFILE
      UDC_AWS_BUCKET: $UDC_AWS_BUCKET
      UDC_JWT_SECRET: $UDC_JWT_SECRET
      UDC_URL: $UDC_URL
  backend-feed:
    image: udagram-api-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      UDC_POSTGRES_USERNAME: $UDC_POSTGRES_USERNAME
      UDC_POSTGRES_PASSWORD: $UDC_POSTGRES_PASSWORD
      UDC_POSTGRES_DB: $UDC_POSTGRES_DB
      UDC_POSTGRES_HOST: $UDC_POSTGRES_HOST
      UDC_AWS_REGION: $UDC_AWS_REGION
      UDC_AWS_PROFILE: $UDC_AWS_PROFILE
      UDC_AWS_BUCKET: $UDC_AWS_BUCKET
      UDC_JWT_SECRET: $UDC_JWT_SECRET
      UDC_URL: $UDC_URL
  frontend:
    image: udagram-frontend
    ports:
      - "8100:80"
